### ISSUE TITLE
Better color pallete

### ISSUE THREAD

**Issue by DGKSK8LIFE** [Rose-OS/Website-Rose#8]

**Comment by AshamedConsequence** [comment]
get the color pallete and I will implement it

**Comment by AshamedConsequence** [comment]
If you are going to ask me to do medial work with no guidelines, you might want to take the liberty to retractively abort yourself

**Comment by DGKSK8LIFE** [comment]
k holup

**Comment by DGKSK8LIFE** [comment]
this one: https://colorpalettes.net/color-palette-4118/

**Comment by DGKSK8LIFE** [comment]
still needs work but looking pretty hot
